# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile
          - black
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        args:
          - --line-length
          - "79"
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
      - id: nbqa
        name: nbqa-autoflake
        args:
          - autoflake
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
        additional_dependencies:
          - autoflake
      - id: nbqa-isort
        args:
          - --profile=black
          - --line-length=120
      - id: nbqa-black
        args:
          - --line-length=120
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
