site_name: {{cookiecutter.project_name}}
site_url: https://example.com/
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repo_name}}
nav:
  - Home: index.md
  - About: about.md
theme: readthedocs
